### ISSUE TITLE
perform thermal analysis of walls and heating element

### ISSUE THREAD

**Issue by DeltaFwulf** [DeltaFwulf/furnace-mk2#2]
calculate wire temperatures and chamber wall power losses at design temperatures

Outputs:
> heating element dT at design temperature
> graphs of results
     - wall thickness vs power
     - wire area vs dT
     - furnace power loss vs chamber temperature
     - wire [area, power, temperature] assuming a cold chamber (STP) to calculate max wire power

**Comment by Stellaramie** [comment]
--- Conservative estimate ---
Chamber dimensions: 76mm of brick, 200mm of rock wool
Required power: 112W @ 1100C
